# Generated by Django 2.2.4 on 2019-09-30 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_type',
            new_name='payment_method',
        ),
    ]
