# Generated by Django 2.2.4 on 2019-10-02 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20191002_1313'),
        ('cook', '0006_auto_20190922_0904'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myCart', '0003_remove_cart_is_ordered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
