# Generated by Django 2.2.4 on 2019-09-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Type',
            field=models.CharField(choices=[('COOK', 'Cook'), ('EATER', 'Eater'), ('BOTH', 'Both')], default=None, max_length=2),
        ),
    ]
