# Generated by Django 2.2.4 on 2019-09-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Type',
            field=models.CharField(choices=[('COOK', 'Cook'), ('EATER', 'Eater'), ('BOTH', 'Both')], default='EATER', max_length=2),
        ),
    ]
