# Generated by Django 2.2.4 on 2019-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
