# Generated by Django 2.2.4 on 2019-09-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_auto_20190919_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('ITALIAN', 'Italian'), ('DESERT', 'Desert'), ('BEVERAGES', 'Beverages'), ('THAI', 'Thai'), ('SUSHI', 'Sushi'), ('INADIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('CHINESE', 'Chinese'), ('AMERICAN', 'American'), ('VIETNAMESE', 'Vietnamese'), ('GLUTEN-FREE', 'Gluten-Free'), ('VEGAN', 'Vegan'), ('SALAD', 'Salad'), ('ASIAN', 'Asian'), ('SOUP', 'Soup'), ('GREEK', 'Greek'), ('JAPANESE', 'Japanese'), ('HOME-COOKING', 'Home-Cooking'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
