# Generated by Django 2.2.4 on 2019-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0004_auto_20190921_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/images/'),
        ),
    ]
