# Generated by Django 2.2.4 on 2019-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0005_auto_20190922_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='images/'),
        ),
    ]
