# Generated by Django 2.2.4 on 2020-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0006_auto_20190922_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('ITALIAN', 'Italian'), ('DESERT', 'Desert'), ('BEVERAGES', 'Beverages'), ('THAI', 'Thai'), ('SUSHI', 'Sushi'), ('INADIAN', 'Indian'), ('MEDITERRANEAN', 'Mediterranean'), ('CHINESE', 'Chinese'), ('AMERICAN', 'American'), ('VIETNAMESE', 'Vietnamese'), ('GLUTEN-FREE', 'Gluten-Free'), ('VEGAN', 'Vegan'), ('SALAD', 'Salad'), ('ASIAN', 'Asian'), ('SOUP', 'Soup'), ('GREEK', 'Greek'), ('JAPANESE', 'Japanese'), ('HOME-COOKING', 'Home-Cooking'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/images'),
        ),
    ]
